### PR TITLE
widen dependency constraint for core_element 0.7.0

### PR DESCRIPTION
**Pull request by kzhdev**
1. widen core_element dependency constraint to 0.7.0
2. moved paper_element into dev_dependencies because it is only matters for example.

### CODE REVIEW

**Comment by zoechi** [comment]
Thanks for your PR!
I published an updated version.
If you would like to be added to the authors list, just add yourself with another PR.

**Comment by kzhdev** [comment]
Added myself in the authors list and updated the changelog in PR #6.

Thanks,
Kun

**Comment by kzhdev** [comment]
@zoechi 

It seems there is something wrong with the new publish 0.1.2. Once I switch to that pub get threw an exception:

Downloading bwu_fontawesome_iconset_svg 0.1.2...
Changed 1 dependency!
Precompiling dependencies...
Loading source assets...
The null object does not have a getter 'pubspec'.

NoSuchMethodError: method not found: 'pubspec'
Receiver: null
Arguments: []
dart:core                                                                                                                       Object.noSuchMethod
/Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/sdk/lib/_internal/pub/lib/src/barback/dependency_computer.dart 251   _PackageDependencyComputer._PackageDependencyComputer
/Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/sdk/lib/_internal/pub/lib/src/barback/dependency_computer.dart 199   DependencyComputer._loadPackageComputer
/Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/sdk/lib/_internal/pub/lib/src/barback/dependency_computer.dart 107   DependencyComputer._transformersNeededByTransformer
/Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/sdk/lib/_internal/pub/lib/src/barback/dependency_computer.dart 258   _PackageDependencyComputer._PackageDependencyComputer
/Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/sdk/lib/_internal/pub/lib/src/barback/dependency_computer.dart 199   DependencyComputer._loadPackageComputer
dart:core                                                                                                                       List.forEach
/Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/sdk/lib/_internal/pub/lib/src/barback/dependency_computer.dart 53    DependencyComputer.DependencyComputer
/Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/sdk/lib/_internal/pub/lib/src/barback/load_all_transformers.dart 33  loadAllTransformers.<async>
dart:isolate

**Comment by kzhdev** [comment]
It works fine if I pull it from my git branch, do you have any idea what could went wrong?

  bwu_fontawesome_iconset_svg:
    git:
      url: git@github.com:kzhdev/bwu_fontawesome_iconset_svg.git
      ref: update_core_element_version

**Comment by zoechi** [comment]
please try `pub cache repair` from command line.

**Comment by kzhdev** [comment]
@zoechi 

pub cache repair does not help. It is a dart bug.

https://code.google.com/p/dart/issues/detail?id=21490.

Changing my dart sdk to dev version fixed the issue.

**Pull request merged**
